/**
 * Theme definitions sourced from tweakcn.com (https://tweakcn.com).
 * Values are raw hex / oklch strings, set directly as CSS custom property values.
 *
 * To add a new theme: paste the dark-mode block from tweakcn and add an entry here.
 * Keys are the CSS variable names without the leading `--`.
 */

export type ThemeVars = Record<string, string>;

// Every var that applyTheme manages — cleared before each switch so themes don't bleed.
export const THEME_VARS: string[] = [
  'background', 'foreground',
  'card', 'card-foreground',
  'popover', 'popover-foreground',
  'primary', 'primary-foreground',
  'secondary', 'secondary-foreground',
  'muted', 'muted-foreground',
  'accent', 'accent-foreground',
  'destructive', 'destructive-foreground',
  'border', 'input', 'ring', 'radius',
  'session-active-bg',
];

export const themes: Record<string, ThemeVars> = {
  // ── Our default (GitHub-dark-inspired) ────────────────────────────────────
  'Dark (Default)': {
    background:               '#0d1117',
    foreground:               '#c9d1d9',
    card:                     '#161b22',
    'card-foreground':        '#c9d1d9',
    popover:                  '#161b22',
    'popover-foreground':     '#c9d1d9',
    primary:                  '#58a6ff',
    'primary-foreground':     '#0d1117',
    secondary:                '#1c2128',
    'secondary-foreground':   '#c9d1d9',
    muted:                    '#1c2128',
    'muted-foreground':       '#8b949e',
    accent:                   '#1f252d',
    'accent-foreground':      '#c9d1d9',
    destructive:              '#f85149',
    'destructive-foreground': '#c9d1d9',
    border:                   '#30363d',
    input:                    '#30363d',
    ring:                     '#58a6ff',
    radius:                   '0.5rem',
    'session-active-bg':      '#1f2d3d',
  },

  // ── tweakcn presets ────────────────────────────────────────────────────────
  'Modern Minimal': {
    background:               '#171717',
    foreground:               '#e5e5e5',
    card:                     '#262626',
    'card-foreground':        '#e5e5e5',
    popover:                  '#262626',
    'popover-foreground':     '#e5e5e5',
    primary:                  '#3b82f6',
    'primary-foreground':     '#ffffff',
    secondary:                '#262626',
    'secondary-foreground':   '#e5e5e5',
    muted:                    '#1f1f1f',
    'muted-foreground':       '#a3a3a3',
    accent:                   '#1e3a8a',
    'accent-foreground':      '#bfdbfe',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#404040',
    input:                    '#404040',
    ring:                     '#3b82f6',
    radius:                   '0.375rem',
    'session-active-bg':      '#1e2d4a',
  },

  'Violet Bloom': {
    background:               '#1a1b1e',
    foreground:               '#f0f0f0',
    card:                     '#222327',
    'card-foreground':        '#f0f0f0',
    popover:                  '#222327',
    'popover-foreground':     '#f0f0f0',
    primary:                  '#8c5cff',
    'primary-foreground':     '#ffffff',
    secondary:                '#2a2c33',
    'secondary-foreground':   '#f0f0f0',
    muted:                    '#2a2c33',
    'muted-foreground':       '#a0a0a0',
    accent:                   '#1e293b',
    'accent-foreground':      '#79c0ff',
    destructive:              '#f87171',
    'destructive-foreground': '#ffffff',
    border:                   '#33353a',
    input:                    '#33353a',
    ring:                     '#8c5cff',
    radius:                   '1.4rem',
    'session-active-bg':      '#2a1f4a',
  },

  'T3 Chat': {
    background:               '#221d27',
    foreground:               '#d2c4de',
    card:                     '#2c2632',
    'card-foreground':        '#dbc5d2',
    popover:                  '#2c2632',
    'popover-foreground':     '#dbc5d2',
    primary:                  '#a3004c',
    'primary-foreground':     '#efc0d8',
    secondary:                '#362d3d',
    'secondary-foreground':   '#d4c7e1',
    muted:                    '#28222d',
    'muted-foreground':       '#c2b6cf',
    accent:                   '#463753',
    'accent-foreground':      '#f8f1f5',
    destructive:              '#301015',
    'destructive-foreground': '#fca5a5',
    border:                   '#3b3237',
    input:                    '#3e343c',
    ring:                     '#db2777',
    radius:                   '0.5rem',
    'session-active-bg':      '#3a2040',
  },

  'Twitter': {
    background:               '#000000',
    foreground:               '#e7e9ea',
    card:                     '#17181c',
    'card-foreground':        '#d9d9d9',
    popover:                  '#17181c',
    'popover-foreground':     '#d9d9d9',
    primary:                  '#1c9cf0',
    'primary-foreground':     '#ffffff',
    secondary:                '#f0f3f4',
    'secondary-foreground':   '#0f1419',
    muted:                    '#181818',
    'muted-foreground':       '#72767a',
    accent:                   '#061622',
    'accent-foreground':      '#1c9cf0',
    destructive:              '#f4212e',
    'destructive-foreground': '#ffffff',
    border:                   '#242628',
    input:                    '#22303c',
    ring:                     '#1da1f2',
    radius:                   '9999px',
    'session-active-bg':      '#0a1e2e',
  },

  'Mocha Mousse': {
    background:               '#2d2521',
    foreground:               '#F1F0E5',
    card:                     '#3c332e',
    'card-foreground':        '#F1F0E5',
    popover:                  '#3c332e',
    'popover-foreground':     '#F1F0E5',
    primary:                  '#C39E88',
    'primary-foreground':     '#2d2521',
    secondary:                '#8A655A',
    'secondary-foreground':   '#F1F0E5',
    muted:                    '#56453F',
    'muted-foreground':       '#c5aa9b',
    accent:                   '#BAAB92',
    'accent-foreground':      '#2d2521',
    destructive:              '#E57373',
    'destructive-foreground': '#ffffff',
    border:                   '#56453F',
    input:                    '#56453F',
    ring:                     '#C39E88',
    radius:                   '0.5rem',
    'session-active-bg':      '#4a3830',
  },

  'Bubblegum': {
    background:               '#12242e',
    foreground:               '#f3e3ea',
    card:                     '#1c2e38',
    'card-foreground':        '#f3e3ea',
    popover:                  '#1c2e38',
    'popover-foreground':     '#f3e3ea',
    primary:                  '#fbe2a7',
    'primary-foreground':     '#12242e',
    secondary:                '#e4a2b1',
    'secondary-foreground':   '#12242e',
    muted:                    '#24272b',
    'muted-foreground':       '#e4a2b1',
    accent:                   '#c67b96',
    'accent-foreground':      '#f3e3ea',
    destructive:              '#e35ea4',
    'destructive-foreground': '#ffffff',
    border:                   '#324859',
    input:                    '#20333d',
    ring:                     '#50afb6',
    radius:                   '0.5rem',
    'session-active-bg':      '#1a3040',
  },

  'Amethyst Haze': {
    background:               '#1a1823',
    foreground:               '#e0ddef',
    card:                     '#232030',
    'card-foreground':        '#e0ddef',
    popover:                  '#232030',
    'popover-foreground':     '#e0ddef',
    primary:                  '#a995c9',
    'primary-foreground':     '#1a1823',
    secondary:                '#5a5370',
    'secondary-foreground':   '#e0ddef',
    muted:                    '#242031',
    'muted-foreground':       '#a09aad',
    accent:                   '#372e3f',
    'accent-foreground':      '#f2b8c6',
    destructive:              '#e57373',
    'destructive-foreground': '#ffffff',
    border:                   '#302c40',
    input:                    '#2a273a',
    ring:                     '#a995c9',
    radius:                   '0.5rem',
    'session-active-bg':      '#2e2540',
  },

  'Notebook': {
    background:               '#2b2b2b',
    foreground:               '#dcdcdc',
    card:                     '#333333',
    'card-foreground':        '#dcdcdc',
    popover:                  '#333333',
    'popover-foreground':     '#dcdcdc',
    primary:                  '#b0b0b0',
    'primary-foreground':     '#2b2b2b',
    secondary:                '#5a5a5a',
    'secondary-foreground':   '#c0c0c0',
    muted:                    '#454545',
    'muted-foreground':       '#a0a0a0',
    accent:                   '#e0e0e0',
    'accent-foreground':      '#333333',
    destructive:              '#d9afaf',
    'destructive-foreground': '#2b2b2b',
    border:                   '#4f4f4f',
    input:                    '#333333',
    ring:                     '#c0c0c0',
    radius:                   '0.625rem',
    'session-active-bg':      '#3a3a3a',
  },

  'Doom 64': {
    background:               '#1a1a1a',
    foreground:               '#e0e0e0',
    card:                     '#2a2a2a',
    'card-foreground':        '#e0e0e0',
    popover:                  '#2a2a2a',
    'popover-foreground':     '#e0e0e0',
    primary:                  '#e53935',
    'primary-foreground':     '#ffffff',
    secondary:                '#689f38',
    'secondary-foreground':   '#000000',
    muted:                    '#252525',
    'muted-foreground':       '#a0a0a0',
    accent:                   '#64b5f6',
    'accent-foreground':      '#000000',
    destructive:              '#ffa000',
    'destructive-foreground': '#000000',
    border:                   '#4a4a4a',
    input:                    '#4a4a4a',
    ring:                     '#e53935',
    radius:                   '0px',
    'session-active-bg':      '#3a1a1a',
  },

  'Catppuccin': {
    background:               '#181825',
    foreground:               '#cdd6f4',
    card:                     '#1e1e2e',
    'card-foreground':        '#cdd6f4',
    popover:                  '#1e1e2e',
    'popover-foreground':     '#cdd6f4',
    primary:                  '#cba6f7',
    'primary-foreground':     '#1e1e2e',
    secondary:                '#585b70',
    'secondary-foreground':   '#cdd6f4',
    muted:                    '#292c3c',
    'muted-foreground':       '#a6adc8',
    accent:                   '#89dceb',
    'accent-foreground':      '#1e1e2e',
    destructive:              '#f38ba8',
    'destructive-foreground': '#1e1e2e',
    border:                   '#313244',
    input:                    '#313244',
    ring:                     '#cba6f7',
    radius:                   '0.5rem',
    'session-active-bg':      '#252540',
  },

  'Graphite': {
    background:               '#1a1a1a',
    foreground:               '#d9d9d9',
    card:                     '#202020',
    'card-foreground':        '#d9d9d9',
    popover:                  '#202020',
    'popover-foreground':     '#d9d9d9',
    primary:                  '#a0a0a0',
    'primary-foreground':     '#1a1a1a',
    secondary:                '#303030',
    'secondary-foreground':   '#d9d9d9',
    muted:                    '#2a2a2a',
    'muted-foreground':       '#808080',
    accent:                   '#404040',
    'accent-foreground':      '#d9d9d9',
    destructive:              '#e06666',
    'destructive-foreground': '#ffffff',
    border:                   '#353535',
    input:                    '#303030',
    ring:                     '#a0a0a0',
    radius:                   '0.5rem',
    'session-active-bg':      '#2a2a2a',
  },

  'Perpetuity': {
    background:               '#0a1a20',
    foreground:               '#4de8e8',
    card:                     '#0c2025',
    'card-foreground':        '#4de8e8',
    popover:                  '#0c2025',
    'popover-foreground':     '#4de8e8',
    primary:                  '#4de8e8',
    'primary-foreground':     '#0a1a20',
    secondary:                '#164955',
    'secondary-foreground':   '#4de8e8',
    muted:                    '#0f3039',
    'muted-foreground':       '#36a5a5',
    accent:                   '#164955',
    'accent-foreground':      '#4de8e8',
    destructive:              '#e83c3c',
    'destructive-foreground': '#ffffff',
    border:                   '#164955',
    input:                    '#164955',
    ring:                     '#4de8e8',
    radius:                   '0.125rem',
    'session-active-bg':      '#0f3040',
  },

  'Kodama Grove': {
    background:               '#3a3529',
    foreground:               '#ede4d4',
    card:                     '#413c33',
    'card-foreground':        '#ede4d4',
    popover:                  '#413c33',
    'popover-foreground':     '#ede4d4',
    primary:                  '#8a9f7b',
    'primary-foreground':     '#2a2521',
    secondary:                '#5a5345',
    'secondary-foreground':   '#ede4d4',
    muted:                    '#4a4439',
    'muted-foreground':       '#a8a096',
    accent:                   '#a18f5c',
    'accent-foreground':      '#2a2521',
    destructive:              '#b5766a',
    'destructive-foreground': '#ffffff',
    border:                   '#5a5345',
    input:                    '#5a5345',
    ring:                     '#8a9f7b',
    radius:                   '0.5rem',
    'session-active-bg':      '#4a4535',
  },

  'Cosmic Night': {
    background:               '#0f0f1a',
    foreground:               '#e2e2f5',
    card:                     '#1a1a2e',
    'card-foreground':        '#e2e2f5',
    popover:                  '#1a1a2e',
    'popover-foreground':     '#e2e2f5',
    primary:                  '#a48fff',
    'primary-foreground':     '#0f0f1a',
    secondary:                '#2d2b55',
    'secondary-foreground':   '#c4c2ff',
    muted:                    '#222244',
    'muted-foreground':       '#a0a0c0',
    accent:                   '#303060',
    'accent-foreground':      '#e2e2f5',
    destructive:              '#ff5470',
    'destructive-foreground': '#ffffff',
    border:                   '#303052',
    input:                    '#303052',
    ring:                     '#a48fff',
    radius:                   '0.5rem',
    'session-active-bg':      '#252550',
  },

  'Tangerine': {
    background:               '#1c2433',
    foreground:               '#e5e5e5',
    card:                     '#2a3040',
    'card-foreground':        '#e5e5e5',
    popover:                  '#2a3040',
    'popover-foreground':     '#e5e5e5',
    primary:                  '#e05d38',
    'primary-foreground':     '#ffffff',
    secondary:                '#2a303e',
    'secondary-foreground':   '#e5e5e5',
    muted:                    '#2a303e',
    'muted-foreground':       '#a3a3a3',
    accent:                   '#2a3656',
    'accent-foreground':      '#bfdbfe',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#3d4354',
    input:                    '#3d4354',
    ring:                     '#e05d38',
    radius:                   '0.5rem',
    'session-active-bg':      '#2a3050',
  },

  'Quantum Rose': {
    background:               '#1a0922',
    foreground:               '#ffb3ff',
    card:                     '#2a1435',
    'card-foreground':        '#ffb3ff',
    popover:                  '#2a1435',
    'popover-foreground':     '#ffb3ff',
    primary:                  '#ff6bef',
    'primary-foreground':     '#180518',
    secondary:                '#46204f',
    'secondary-foreground':   '#ffb3ff',
    muted:                    '#331941',
    'muted-foreground':       '#d67ad6',
    accent:                   '#5a1f5d',
    'accent-foreground':      '#ffb3ff',
    destructive:              '#ff2876',
    'destructive-foreground': '#ffffff',
    border:                   '#4a1b5f',
    input:                    '#46204f',
    ring:                     '#ff6bef',
    radius:                   '0.5rem',
    'session-active-bg':      '#3a1550',
  },

  'Nature': {
    background:               '#1c2a1f',
    foreground:               '#f0ebe5',
    card:                     '#2d3a2e',
    'card-foreground':        '#f0ebe5',
    popover:                  '#2d3a2e',
    'popover-foreground':     '#f0ebe5',
    primary:                  '#4caf50',
    'primary-foreground':     '#0a1f0c',
    secondary:                '#3e4a3d',
    'secondary-foreground':   '#d7e0d6',
    muted:                    '#252f26',
    'muted-foreground':       '#d7cfc4',
    accent:                   '#388e3c',
    'accent-foreground':      '#f0ebe5',
    destructive:              '#c62828',
    'destructive-foreground': '#ffffff',
    border:                   '#3e4a3d',
    input:                    '#3e4a3d',
    ring:                     '#4caf50',
    radius:                   '0.5rem',
    'session-active-bg':      '#253528',
  },

  'Bold Tech': {
    background:               '#0f172a',
    foreground:               '#e0e7ff',
    card:                     '#1e1b4b',
    'card-foreground':        '#e0e7ff',
    popover:                  '#1e1b4b',
    'popover-foreground':     '#e0e7ff',
    primary:                  '#8b5cf6',
    'primary-foreground':     '#ffffff',
    secondary:                '#1e1b4b',
    'secondary-foreground':   '#e0e7ff',
    muted:                    '#171447',
    'muted-foreground':       '#c4b5fd',
    accent:                   '#4338ca',
    'accent-foreground':      '#e0e7ff',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#2e1065',
    input:                    '#2e1065',
    ring:                     '#8b5cf6',
    radius:                   '0.625rem',
    'session-active-bg':      '#2a1a5e',
  },

  'Elegant Luxury': {
    background:               '#1c1917',
    foreground:               '#f5f5f4',
    card:                     '#292524',
    'card-foreground':        '#f5f5f4',
    popover:                  '#292524',
    'popover-foreground':     '#f5f5f4',
    primary:                  '#b91c1c',
    'primary-foreground':     '#faf7f5',
    secondary:                '#92400e',
    'secondary-foreground':   '#fef3c7',
    muted:                    '#1f1c1a',
    'muted-foreground':       '#d6d3d1',
    accent:                   '#b45309',
    'accent-foreground':      '#fef3c7',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#44403c',
    input:                    '#44403c',
    ring:                     '#b91c1c',
    radius:                   '0.375rem',
    'session-active-bg':      '#3a2020',
  },

  'Amber Minimal': {
    background:               '#171717',
    foreground:               '#e5e5e5',
    card:                     '#262626',
    'card-foreground':        '#e5e5e5',
    popover:                  '#262626',
    'popover-foreground':     '#e5e5e5',
    primary:                  '#f59e0b',
    'primary-foreground':     '#000000',
    secondary:                '#262626',
    'secondary-foreground':   '#e5e5e5',
    muted:                    '#1f1f1f',
    'muted-foreground':       '#a3a3a3',
    accent:                   '#92400e',
    'accent-foreground':      '#fde68a',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#404040',
    input:                    '#404040',
    ring:                     '#f59e0b',
    radius:                   '0.5rem',
    'session-active-bg':      '#3a2a10',
  },

  'Supabase': {
    background:               '#121212',
    foreground:               '#e2e8f0',
    card:                     '#171717',
    'card-foreground':        '#e2e8f0',
    popover:                  '#171717',
    'popover-foreground':     '#e2e8f0',
    primary:                  '#3ecf8e',
    'primary-foreground':     '#121212',
    secondary:                '#242424',
    'secondary-foreground':   '#fafafa',
    muted:                    '#1f1f1f',
    'muted-foreground':       '#a2a2a2',
    accent:                   '#313131',
    'accent-foreground':      '#fafafa',
    destructive:              '#f87171',
    'destructive-foreground': '#ffffff',
    border:                   '#292929',
    input:                    '#242424',
    ring:                     '#3ecf8e',
    radius:                   '0.375rem',
    'session-active-bg':      '#1a2e25',
  },

  'Neo Brutalism': {
    background:               '#000000',
    foreground:               '#ffffff',
    card:                     '#333333',
    'card-foreground':        '#ffffff',
    popover:                  '#333333',
    'popover-foreground':     '#ffffff',
    primary:                  '#ff6666',
    'primary-foreground':     '#000000',
    secondary:                '#ffff33',
    'secondary-foreground':   '#000000',
    muted:                    '#1a1a1a',
    'muted-foreground':       '#cccccc',
    accent:                   '#3399ff',
    'accent-foreground':      '#000000',
    destructive:              '#ffffff',
    'destructive-foreground': '#000000',
    border:                   '#ffffff',
    input:                    '#ffffff',
    ring:                     '#ff6666',
    radius:                   '0px',
    'session-active-bg':      '#2a1a1a',
  },

  'Solar Dusk': {
    background:               '#1C1917',
    foreground:               '#F5F5F4',
    card:                     '#292524',
    'card-foreground':        '#F5F5F4',
    popover:                  '#292524',
    'popover-foreground':     '#F5F5F4',
    primary:                  '#F97316',
    'primary-foreground':     '#FFFFFF',
    secondary:                '#57534E',
    'secondary-foreground':   '#E7E5E4',
    muted:                    '#201d1a',
    'muted-foreground':       '#A8A29E',
    accent:                   '#1e4252',
    'accent-foreground':      '#E7E5E4',
    destructive:              '#DC2626',
    'destructive-foreground': '#ffffff',
    border:                   '#44403C',
    input:                    '#44403C',
    ring:                     '#F97316',
    radius:                   '0.3rem',
    'session-active-bg':      '#3a2a10',
  },

  'Claymorphism': {
    background:               '#1e1b18',
    foreground:               '#e2e8f0',
    card:                     '#2c2825',
    'card-foreground':        '#e2e8f0',
    popover:                  '#2c2825',
    'popover-foreground':     '#e2e8f0',
    primary:                  '#818cf8',
    'primary-foreground':     '#1e1b18',
    secondary:                '#3a3633',
    'secondary-foreground':   '#d1d5db',
    muted:                    '#1f1c19',
    'muted-foreground':       '#9ca3af',
    accent:                   '#484441',
    'accent-foreground':      '#d1d5db',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#3a3633',
    input:                    '#3a3633',
    ring:                     '#818cf8',
    radius:                   '1.25rem',
    'session-active-bg':      '#2a2860',
  },

  'Cyberpunk': {
    background:               '#0c0c1d',
    foreground:               '#eceff4',
    card:                     '#1e1e3f',
    'card-foreground':        '#eceff4',
    popover:                  '#1e1e3f',
    'popover-foreground':     '#eceff4',
    primary:                  '#ff00c8',
    'primary-foreground':     '#ffffff',
    secondary:                '#1e1e3f',
    'secondary-foreground':   '#eceff4',
    muted:                    '#151530',
    'muted-foreground':       '#8085a6',
    accent:                   '#00ffcc',
    'accent-foreground':      '#0c0c1d',
    destructive:              '#ff3d00',
    'destructive-foreground': '#ffffff',
    border:                   '#2e2e5e',
    input:                    '#2e2e5e',
    ring:                     '#ff00c8',
    radius:                   '0.5rem',
    'session-active-bg':      '#1a1040',
  },

  'Pastel Dreams': {
    background:               '#1c1917',
    foreground:               '#e0e7ff',
    card:                     '#2d2535',
    'card-foreground':        '#e0e7ff',
    popover:                  '#2d2535',
    'popover-foreground':     '#e0e7ff',
    primary:                  '#c0aafd',
    'primary-foreground':     '#1c1917',
    secondary:                '#3f324a',
    'secondary-foreground':   '#d1d5db',
    muted:                    '#20182b',
    'muted-foreground':       '#9ca3af',
    accent:                   '#4a3d5a',
    'accent-foreground':      '#d1d5db',
    destructive:              '#fca5a5',
    'destructive-foreground': '#1c1917',
    border:                   '#3f324a',
    input:                    '#3f324a',
    ring:                     '#c0aafd',
    radius:                   '1.5rem',
    'session-active-bg':      '#352a50',
  },

  'Clean Slate': {
    background:               '#0f172a',
    foreground:               '#e2e8f0',
    card:                     '#1e293b',
    'card-foreground':        '#e2e8f0',
    popover:                  '#1e293b',
    'popover-foreground':     '#e2e8f0',
    primary:                  '#818cf8',
    'primary-foreground':     '#0f172a',
    secondary:                '#2d3748',
    'secondary-foreground':   '#d1d5db',
    muted:                    '#152032',
    'muted-foreground':       '#9ca3af',
    accent:                   '#374151',
    'accent-foreground':      '#d1d5db',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#4b5563',
    input:                    '#4b5563',
    ring:                     '#818cf8',
    radius:                   '0.5rem',
    'session-active-bg':      '#252a50',
  },

  'Caffeine': {
    background:               '#111111',
    foreground:               '#eeeeee',
    card:                     '#191919',
    'card-foreground':        '#eeeeee',
    popover:                  '#191919',
    'popover-foreground':     '#eeeeee',
    primary:                  '#ffe0c2',
    'primary-foreground':     '#081a1b',
    secondary:                '#393028',
    'secondary-foreground':   '#ffe0c2',
    muted:                    '#222222',
    'muted-foreground':       '#b4b4b4',
    accent:                   '#2a2a2a',
    'accent-foreground':      '#eeeeee',
    destructive:              '#e54d2e',
    'destructive-foreground': '#ffffff',
    border:                   '#201e18',
    input:                    '#484848',
    ring:                     '#ffe0c2',
    radius:                   '0.5rem',
    'session-active-bg':      '#2a2010',
  },

  'Ocean Breeze': {
    background:               '#0f172a',
    foreground:               '#d1d5db',
    card:                     '#1e293b',
    'card-foreground':        '#d1d5db',
    popover:                  '#1e293b',
    'popover-foreground':     '#d1d5db',
    primary:                  '#34d399',
    'primary-foreground':     '#0f172a',
    secondary:                '#2d3748',
    'secondary-foreground':   '#a1a1aa',
    muted:                    '#19212e',
    'muted-foreground':       '#6b7280',
    accent:                   '#374151',
    'accent-foreground':      '#a1a1aa',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#4b5563',
    input:                    '#4b5563',
    ring:                     '#34d399',
    radius:                   '0.5rem',
    'session-active-bg':      '#1a3040',
  },

  'Retro Arcade': {
    background:               '#002b36',
    foreground:               '#93a1a1',
    card:                     '#073642',
    'card-foreground':        '#93a1a1',
    popover:                  '#073642',
    'popover-foreground':     '#93a1a1',
    primary:                  '#d33682',
    'primary-foreground':     '#ffffff',
    secondary:                '#2aa198',
    'secondary-foreground':   '#ffffff',
    muted:                    '#586e75',
    'muted-foreground':       '#93a1a1',
    accent:                   '#cb4b16',
    'accent-foreground':      '#ffffff',
    destructive:              '#dc322f',
    'destructive-foreground': '#ffffff',
    border:                   '#586e75',
    input:                    '#586e75',
    ring:                     '#d33682',
    radius:                   '0.25rem',
    'session-active-bg':      '#0a3040',
  },

  'Midnight Bloom': {
    background:               '#1a1d23',
    foreground:               '#e5e5e5',
    card:                     '#2f3436',
    'card-foreground':        '#e5e5e5',
    popover:                  '#2f3436',
    'popover-foreground':     '#e5e5e5',
    primary:                  '#6c5ce7',
    'primary-foreground':     '#ffffff',
    secondary:                '#4b0082',
    'secondary-foreground':   '#e5e5e5',
    muted:                    '#444444',
    'muted-foreground':       '#a3a3a3',
    accent:                   '#6495ed',
    'accent-foreground':      '#e5e5e5',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#444444',
    input:                    '#444444',
    ring:                     '#6c5ce7',
    radius:                   '0.5rem',
    'session-active-bg':      '#282060',
  },

  'Northern Lights': {
    background:               '#1a1d23',
    foreground:               '#e5e5e5',
    card:                     '#2f3436',
    'card-foreground':        '#e5e5e5',
    popover:                  '#2f3436',
    'popover-foreground':     '#e5e5e5',
    primary:                  '#34a85a',
    'primary-foreground':     '#ffffff',
    secondary:                '#4682b4',
    'secondary-foreground':   '#e5e5e5',
    muted:                    '#444444',
    'muted-foreground':       '#a3a3a3',
    accent:                   '#6495ed',
    'accent-foreground':      '#e5e5e5',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#444444',
    input:                    '#444444',
    ring:                     '#34a85a',
    radius:                   '0.5rem',
    'session-active-bg':      '#1a3030',
  },

  'Vintage Paper': {
    background:               '#2d2621',
    foreground:               '#ece5d8',
    card:                     '#3a322c',
    'card-foreground':        '#ece5d8',
    popover:                  '#3a322c',
    'popover-foreground':     '#ece5d8',
    primary:                  '#c0a080',
    'primary-foreground':     '#2d2621',
    secondary:                '#4a4039',
    'secondary-foreground':   '#ece5d8',
    muted:                    '#312b26',
    'muted-foreground':       '#c5bcac',
    accent:                   '#59493e',
    'accent-foreground':      '#ece5d8',
    destructive:              '#b54a35',
    'destructive-foreground': '#ffffff',
    border:                   '#4a4039',
    input:                    '#4a4039',
    ring:                     '#c0a080',
    radius:                   '0.25rem',
    'session-active-bg':      '#3a3020',
  },

  'Sunset Horizon': {
    background:               '#2a2024',
    foreground:               '#f2e9e4',
    card:                     '#392f35',
    'card-foreground':        '#f2e9e4',
    popover:                  '#392f35',
    'popover-foreground':     '#f2e9e4',
    primary:                  '#ff7e5f',
    'primary-foreground':     '#ffffff',
    secondary:                '#463a41',
    'secondary-foreground':   '#f2e9e4',
    muted:                    '#30272c',
    'muted-foreground':       '#d7c6bc',
    accent:                   '#feb47b',
    'accent-foreground':      '#2a2024',
    destructive:              '#e63946',
    'destructive-foreground': '#ffffff',
    border:                   '#463a41',
    input:                    '#463a41',
    ring:                     '#ff7e5f',
    radius:                   '0.625rem',
    'session-active-bg':      '#3a2020',
  },

  'Starry Night': {
    background:               '#181a24',
    foreground:               '#e6eaf3',
    card:                     '#23243a',
    'card-foreground':        '#e6eaf3',
    popover:                  '#23243a',
    'popover-foreground':     '#e6eaf3',
    primary:                  '#3a5ba0',
    'primary-foreground':     '#ffe066',
    secondary:                '#ffe066',
    'secondary-foreground':   '#23243a',
    muted:                    '#1d1e2f',
    'muted-foreground':       '#7a88a1',
    accent:                   '#bccdf0',
    'accent-foreground':      '#181a24',
    destructive:              '#a04a6c',
    'destructive-foreground': '#ffffff',
    border:                   '#2d2e3e',
    input:                    '#3a5ba0',
    ring:                     '#ffe066',
    radius:                   '0.5rem',
    'session-active-bg':      '#1e2540',
  },

  'Claude': {
    background:               '#262624',
    foreground:               '#faf9f5',
    card:                     '#262624',
    'card-foreground':        '#faf9f5',
    popover:                  '#262624',
    'popover-foreground':     '#faf9f5',
    primary:                  '#d97757',
    'primary-foreground':     '#ffffff',
    secondary:                '#faf9f5',
    'secondary-foreground':   '#30302e',
    muted:                    '#1b1b19',
    'muted-foreground':       '#b7b5a9',
    accent:                   '#1a1915',
    'accent-foreground':      '#f5f4ee',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#3e3e38',
    input:                    '#52514a',
    ring:                     '#d97757',
    radius:                   '0.5rem',
    'session-active-bg':      '#2a2520',
  },

  'Vercel': {
    background:               'oklch(0 0 0)',
    foreground:               'oklch(1.00 0 0)',
    card:                     'oklch(0.14 0 0)',
    'card-foreground':        'oklch(1.00 0 0)',
    popover:                  'oklch(0.14 0 0)',
    'popover-foreground':     'oklch(1.00 0 0)',
    primary:                  'oklch(1.00 0 0)',
    'primary-foreground':     'oklch(0 0 0)',
    secondary:                'oklch(0.25 0 0)',
    'secondary-foreground':   'oklch(1.00 0 0)',
    muted:                    'oklch(0.23 0 0)',
    'muted-foreground':       'oklch(0.72 0 0)',
    accent:                   'oklch(0.32 0 0)',
    'accent-foreground':      'oklch(1.00 0 0)',
    destructive:              'oklch(0.69 0.20 23.91)',
    'destructive-foreground': 'oklch(1.00 0 0)',
    border:                   'oklch(0.26 0 0)',
    input:                    'oklch(0.32 0 0)',
    ring:                     'oklch(0.72 0 0)',
    radius:                   '0.5rem',
    'session-active-bg':      'oklch(0.20 0 0)',
  },

  'Darkmatter': {
    background:               '#121113',
    foreground:               '#c1c1c1',
    card:                     '#121212',
    'card-foreground':        '#c1c1c1',
    popover:                  '#121212',
    'popover-foreground':     '#c1c1c1',
    primary:                  '#e78a53',
    'primary-foreground':     '#121113',
    secondary:                '#5f8787',
    'secondary-foreground':   '#121113',
    muted:                    '#222222',
    'muted-foreground':       '#888888',
    accent:                   '#333333',
    'accent-foreground':      '#c1c1c1',
    destructive:              '#5f8787',
    'destructive-foreground': '#121113',
    border:                   '#222222',
    input:                    '#222222',
    ring:                     '#e78a53',
    radius:                   '0.5rem',
    'session-active-bg':      '#2a2018',
  },

  'Mono': {
    background:               '#0a0a0a',
    foreground:               '#fafafa',
    card:                     '#191919',
    'card-foreground':        '#fafafa',
    popover:                  '#191919',
    'popover-foreground':     '#fafafa',
    primary:                  '#737373',
    'primary-foreground':     '#fafafa',
    secondary:                '#262626',
    'secondary-foreground':   '#fafafa',
    muted:                    '#262626',
    'muted-foreground':       '#a1a1a1',
    accent:                   '#404040',
    'accent-foreground':      '#fafafa',
    destructive:              '#ff6467',
    'destructive-foreground': '#ffffff',
    border:                   '#383838',
    input:                    '#525252',
    ring:                     '#737373',
    radius:                   '0.5rem',
    'session-active-bg':      '#202020',
  },

  'Soft Pop': {
    background:               '#000000',
    foreground:               '#ffffff',
    card:                     '#1a212b',
    'card-foreground':        '#ffffff',
    popover:                  '#1a212b',
    'popover-foreground':     '#ffffff',
    primary:                  '#818cf8',
    'primary-foreground':     '#000000',
    secondary:                '#2dd4bf',
    'secondary-foreground':   '#000000',
    muted:                    '#333333',
    'muted-foreground':       '#cccccc',
    accent:                   '#fcd34d',
    'accent-foreground':      '#000000',
    destructive:              '#f87171',
    'destructive-foreground': '#ffffff',
    border:                   '#545454',
    input:                    '#ffffff',
    ring:                     '#818cf8',
    radius:                   '1rem',
    'session-active-bg':      '#1a1a40',
  },

  'Sage Garden': {
    background:               '#0a0a0a',
    foreground:               '#f5f5f5',
    card:                     '#121212',
    'card-foreground':        '#f5f5f5',
    popover:                  '#121212',
    'popover-foreground':     '#f5f5f5',
    primary:                  '#7c9082',
    'primary-foreground':     '#000000',
    secondary:                '#1a1a1a',
    'secondary-foreground':   '#f5f5f5',
    muted:                    '#1a1a1a',
    'muted-foreground':       '#a0a0a0',
    accent:                   '#36443a',
    'accent-foreground':      '#f5f5f5',
    destructive:              '#ef4444',
    'destructive-foreground': '#ffffff',
    border:                   '#2a2a2a',
    input:                    '#121212',
    ring:                     '#7c9082',
    radius:                   '0.5rem',
    'session-active-bg':      '#1a2a1e',
  },
};

export const themeNames: string[] = Object.keys(themes);
export const DEFAULT_THEME: string = themeNames[0];

export function applyTheme(name: string): void {
  const vars = themes[name] ?? themes[DEFAULT_THEME];
  const root = document.documentElement;
  for (const v of THEME_VARS) {
    root.style.removeProperty(`--${v}`);
  }
  for (const [key, value] of Object.entries(vars)) {
    root.style.setProperty(`--${key}`, value);
  }
}
